// Студия плагинов Minecraft: генерация проектов Paper/Spigot и компиляция.
const fs = require('fs');
const path = require('path');
const { spawn, exec } = require('child_process');

const system = require('./system');

function mcRoot() {
  const root = path.join(system.safeRoot(), 'minecraft-plugins');
  fs.mkdirSync(root, { recursive: true });
  return root;
}

function checkEnv() {
  const check = (cmd) => new Promise((res) => exec(cmd, (err, stdout, stderr) => res(err ? null : (stdout || stderr).split('\n')[0].trim())));
  return Promise.all([check('java -version 2>&1'), check('mvn -v')]).then(([java, mvn]) => ({
    java: !!java, javaVersion: java || null,
    maven: !!mvn, mavenVersion: mvn || null,
    hints: {
      java: 'winget install Microsoft.OpenJDK.21',
      maven: 'winget install Apache.Maven'
    }
  }));
}

function listProjects() {
  const root = mcRoot();
  return fs.readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => {
      const dir = path.join(root, d.name);
      const jar = findJar(dir);
      return { name: d.name, dir, jar, hasPom: fs.existsSync(path.join(dir, 'pom.xml')) };
    });
}

function findJar(dir) {
  const target = path.join(dir, 'target');
  if (!fs.existsSync(target)) return null;
  const jars = fs.readdirSync(target).filter((f) => f.endsWith('.jar') && !f.includes('original'));
  return jars.length ? path.join(target, jars[0]) : null;
}

// Шаблоны плагинов: базовый, с командой, со слушателем событий.
const TEMPLATES = {
  basic: { label: 'Базовый плагин', desc: 'Минимальный плагин: onEnable/onDisable.' },
  command: { label: 'Плагин с командой', desc: 'Пример своей команды /hello с обработчиком.' },
  listener: { label: 'Слушатель событий', desc: 'Реагирует на вход игрока (приветствие + эффекты).' }
};

function javaClassName(name) {
  const clean = name.replace(/[^a-zA-Z0-9]/g, '');
  return (clean.charAt(0).toUpperCase() + clean.slice(1)) || 'MyPlugin';
}

function createProject({ name, template = 'basic', mcVersion = '1.21', author = 'NexusAI' }) {
  const safe = name.replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 40) || 'MyPlugin';
  const cls = javaClassName(safe);
  const pkg = 'com.nexusai.' + safe.toLowerCase();
  const dir = path.join(mcRoot(), safe);
  if (fs.existsSync(dir)) return { ok: false, error: 'Проект с таким именем уже существует' };

  const javaDir = path.join(dir, 'src/main/java', ...pkg.split('.'));
  const resDir = path.join(dir, 'src/main/resources');
  fs.mkdirSync(javaDir, { recursive: true });
  fs.mkdirSync(resDir, { recursive: true });

  const apiVersion = mcVersion.split('.').slice(0, 2).join('.');

  fs.writeFileSync(path.join(dir, 'pom.xml'), `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>${pkg}</groupId>
  <artifactId>${safe.toLowerCase()}</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>
  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <repositories>
    <repository>
      <id>papermc</id>
      <url>https://repo.papermc.io/repository/maven-public/</url>
    </repository>
  </repositories>
  <dependencies>
    <dependency>
      <groupId>io.papermc.paper</groupId>
      <artifactId>paper-api</artifactId>
      <version>${mcVersion}-R0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <build>
    <finalName>${safe}</finalName>
  </build>
</project>
`);

  fs.writeFileSync(path.join(resDir, 'plugin.yml'), `name: ${safe}
version: 1.0.0
main: ${pkg}.${cls}
api-version: '${apiVersion}'
author: ${author}
description: Plugin generated by Nexus AI Hub
${template === 'command' ? `commands:
  hello:
    description: Say hello
    usage: /hello
` : ''}`);

  let body;
  if (template === 'command') {
    body = `package ${pkg};

import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.plugin.java.JavaPlugin;

public class ${cls} extends JavaPlugin {
    @Override
    public void onEnable() {
        getLogger().info("${cls} enabled!");
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (command.getName().equalsIgnoreCase("hello")) {
            sender.sendMessage("§aПривет от ${cls}! Плагин создан в Nexus AI Hub.");
            return true;
        }
        return false;
    }

    @Override
    public void onDisable() {
        getLogger().info("${cls} disabled.");
    }
}
`;
  } else if (template === 'listener') {
    body = `package ${pkg};

import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.plugin.java.JavaPlugin;

public class ${cls} extends JavaPlugin implements Listener {
    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
        getLogger().info("${cls} enabled!");
    }

    @EventHandler
    public void onJoin(PlayerJoinEvent event) {
        event.getPlayer().sendMessage("§bДобро пожаловать, " + event.getPlayer().getName() + "!");
    }

    @Override
    public void onDisable() {
        getLogger().info("${cls} disabled.");
    }
}
`;
  } else {
    body = `package ${pkg};

import org.bukkit.plugin.java.JavaPlugin;

public class ${cls} extends JavaPlugin {
    @Override
    public void onEnable() {
        getLogger().info("${cls} enabled!");
    }

    @Override
    public void onDisable() {
        getLogger().info("${cls} disabled.");
    }
}
`;
  }
  fs.writeFileSync(path.join(javaDir, cls + '.java'), body);
  return { ok: true, name: safe, dir, mainClass: `${pkg}.${cls}` };
}

// Компиляция через Maven со стримингом лога в UI.
function compileProject(name, onLog) {
  return new Promise(async (resolve) => {
    const dir = path.join(mcRoot(), name);
    if (!fs.existsSync(path.join(dir, 'pom.xml'))) return resolve({ ok: false, error: 'pom.xml не найден' });
    const env = await checkEnv();
    if (!env.java) return resolve({ ok: false, error: 'Java не установлена. Выполните: ' + env.hints.java });
    if (!env.maven) return resolve({ ok: false, error: 'Maven не установлен. Выполните: ' + env.hints.maven });

    const cmd = process.platform === 'win32' ? 'mvn.cmd' : 'mvn';
    const proc = spawn(cmd, ['-q', '-B', 'package'], { cwd: dir, shell: process.platform === 'win32' });
    let log = '';
    const push = (d) => { log += d; onLog && onLog(String(d)); };
    proc.stdout.on('data', push);
    proc.stderr.on('data', push);
    const timer = setTimeout(() => { proc.kill(); resolve({ ok: false, error: 'Таймаут сборки (10 мин)', log }); }, 600000);
    proc.on('close', (code) => {
      clearTimeout(timer);
      const jar = findJar(dir);
      resolve(code === 0 && jar
        ? { ok: true, jar, log }
        : { ok: false, error: 'Сборка завершилась с ошибкой (код ' + code + ')', log });
    });
    proc.on('error', (e) => { clearTimeout(timer); resolve({ ok: false, error: e.message, log }); });
  });
}

function deleteProject(name) {
  const dir = path.join(mcRoot(), name.replace(/[^a-zA-Z0-9_-]/g, ''));
  if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
  return { ok: true };
}

/* ------ Инструменты для агентов ------ */
const toolSchemas = [
  { type: 'function', function: { name: 'mc_create_plugin', description: 'Создать новый проект плагина Minecraft (Paper/Spigot) из шаблона. Шаблоны: basic, command, listener.', parameters: { type: 'object', properties: { name: { type: 'string' }, template: { type: 'string' }, mcVersion: { type: 'string' } }, required: ['name'] } } },
  { type: 'function', function: { name: 'mc_compile_plugin', description: 'Скомпилировать проект плагина Minecraft в .jar через Maven. Возвращает путь к jar или лог ошибок.', parameters: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'] } } },
  { type: 'function', function: { name: 'mc_list_plugins', description: 'Показать список проектов плагинов Minecraft.', parameters: { type: 'object', properties: {} } } }
];

const toolHandlers = {
  async mc_create_plugin(args) {
    const r = createProject(args);
    return r.ok ? `Проект создан: ${r.dir}\nГлавный класс: ${r.mainClass}\nИсходники можно править через write_file.` : 'Ошибка: ' + r.error;
  },
  async mc_compile_plugin({ name }) {
    const r = await compileProject(name, null);
    return r.ok ? 'Готово! JAR: ' + r.jar : 'Ошибка сборки: ' + r.error + '\n' + String(r.log || '').slice(-1500);
  },
  async mc_list_plugins() {
    const list = listProjects();
    return list.length ? list.map((p) => `${p.name}${p.jar ? ' [собран: ' + p.jar + ']' : ''}`).join('\n') : 'Проектов нет.';
  }
};

module.exports = { mcRoot, checkEnv, listProjects, createProject, compileProject, deleteProject, TEMPLATES, toolSchemas, toolHandlers };
