// Студия плагинов Minecraft: генерация проектов Paper/Spigot и компиляция.
const fs = require('fs');
const path = require('path');
const { spawn, exec } = require('child_process');

const system = require('./system');

function mcRoot() {
  const root = path.join(system.safeRoot(), 'minecraft-plugins');
  fs.mkdirSync(root, { recursive: true });
  return root;
}

function checkEnv() {
  const check = (cmd) => new Promise((res) => exec(cmd, (err, stdout, stderr) => res(err ? null : (stdout || stderr).split('\n')[0].trim())));
  return Promise.all([check('java -version 2>&1'), check('mvn -v'), check('gradle -v')]).then(([java, mvn, gradle]) => ({
    java: !!java, javaVersion: java || null,
    maven: !!mvn, mavenVersion: mvn || null,
    gradle: !!gradle, gradleVersion: gradle || null,
    hints: {
      java: 'winget install Microsoft.OpenJDK.21',
      maven: 'winget install Apache.Maven',
      gradle: 'winget install Gradle.Gradle'
    }
  }));
}

function listProjects() {
  const root = mcRoot();
  return fs.readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => {
      const dir = path.join(root, d.name);
      const jar = findJar(dir);
      const kind = projectKind(dir);
      return { name: d.name, dir, jar, kind, hasPom: fs.existsSync(path.join(dir, 'pom.xml')), buildable: fs.existsSync(path.join(dir, 'pom.xml')) || fs.existsSync(path.join(dir, 'build.gradle')) };
    });
}

function findJar(dir) {
  // Maven кладёт jar в target/, Gradle — в build/libs/.
  for (const sub of ['target', 'build/libs']) {
    const d = path.join(dir, sub);
    if (!fs.existsSync(d)) continue;
    const jars = fs.readdirSync(d).filter((f) => f.endsWith('.jar') && !f.includes('original') && !f.includes('-sources') && !f.includes('-dev'));
    if (jars.length) return path.join(d, jars[0]);
  }
  return null;
}

function projectKind(dir) {
  if (fs.existsSync(path.join(dir, 'pom.xml'))) return 'plugin';
  if (fs.existsSync(path.join(dir, 'src/main/resources/fabric.mod.json'))) return 'fabric';
  if (fs.existsSync(path.join(dir, 'build.gradle'))) return 'forge';
  return 'plugin';
}

// Шаблоны плагинов: базовый, с командой, со слушателем событий.
const TEMPLATES = {
  basic: { label: 'Базовый плагин', desc: 'Минимальный плагин: onEnable/onDisable.' },
  command: { label: 'Плагин с командой', desc: 'Пример своей команды /hello с обработчиком.' },
  listener: { label: 'Слушатель событий', desc: 'Реагирует на вход игрока (приветствие + эффекты).' }
};

function javaClassName(name) {
  const clean = name.replace(/[^a-zA-Z0-9]/g, '');
  return (clean.charAt(0).toUpperCase() + clean.slice(1)) || 'MyPlugin';
}

function createProject({ name, template = 'basic', mcVersion = '1.21', author = 'MytheraAI' }) {
  const safe = name.replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 40) || 'MyPlugin';
  const cls = javaClassName(safe);
  const pkg = 'com.mythera.' + safe.toLowerCase();
  const dir = path.join(mcRoot(), safe);
  if (fs.existsSync(dir)) return { ok: false, error: 'Проект с таким именем уже существует' };

  const javaDir = path.join(dir, 'src/main/java', ...pkg.split('.'));
  const resDir = path.join(dir, 'src/main/resources');
  fs.mkdirSync(javaDir, { recursive: true });
  fs.mkdirSync(resDir, { recursive: true });

  const apiVersion = mcVersion.split('.').slice(0, 2).join('.');

  fs.writeFileSync(path.join(dir, 'pom.xml'), `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>${pkg}</groupId>
  <artifactId>${safe.toLowerCase()}</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>
  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <repositories>
    <repository>
      <id>papermc</id>
      <url>https://repo.papermc.io/repository/maven-public/</url>
    </repository>
  </repositories>
  <dependencies>
    <dependency>
      <groupId>io.papermc.paper</groupId>
      <artifactId>paper-api</artifactId>
      <version>${mcVersion}-R0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <build>
    <finalName>${safe}</finalName>
  </build>
</project>
`);

  fs.writeFileSync(path.join(resDir, 'plugin.yml'), `name: ${safe}
version: 1.0.0
main: ${pkg}.${cls}
api-version: '${apiVersion}'
author: ${author}
description: Plugin generated by Mythera AI Hub
${template === 'command' ? `commands:
  hello:
    description: Say hello
    usage: /hello
` : ''}`);

  let body;
  if (template === 'command') {
    body = `package ${pkg};

import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.plugin.java.JavaPlugin;

public class ${cls} extends JavaPlugin {
    @Override
    public void onEnable() {
        getLogger().info("${cls} enabled!");
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (command.getName().equalsIgnoreCase("hello")) {
            sender.sendMessage("§aПривет от ${cls}! Плагин создан в Mythera AI Hub.");
            return true;
        }
        return false;
    }

    @Override
    public void onDisable() {
        getLogger().info("${cls} disabled.");
    }
}
`;
  } else if (template === 'listener') {
    body = `package ${pkg};

import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.plugin.java.JavaPlugin;

public class ${cls} extends JavaPlugin implements Listener {
    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
        getLogger().info("${cls} enabled!");
    }

    @EventHandler
    public void onJoin(PlayerJoinEvent event) {
        event.getPlayer().sendMessage("§bДобро пожаловать, " + event.getPlayer().getName() + "!");
    }

    @Override
    public void onDisable() {
        getLogger().info("${cls} disabled.");
    }
}
`;
  } else {
    body = `package ${pkg};

import org.bukkit.plugin.java.JavaPlugin;

public class ${cls} extends JavaPlugin {
    @Override
    public void onEnable() {
        getLogger().info("${cls} enabled!");
    }

    @Override
    public void onDisable() {
        getLogger().info("${cls} disabled.");
    }
}
`;
  }
  fs.writeFileSync(path.join(javaDir, cls + '.java'), body);
  return { ok: true, name: safe, dir, mainClass: `${pkg}.${cls}` };
}

// Компиляция через Maven со стримингом лога в UI.
function compileProject(name, onLog) {
  return new Promise(async (resolve) => {
    const dir = path.join(mcRoot(), name);
    if (!fs.existsSync(path.join(dir, 'pom.xml'))) return resolve({ ok: false, error: 'pom.xml не найден' });
    const env = await checkEnv();
    if (!env.java) return resolve({ ok: false, error: 'Java не установлена. Выполните: ' + env.hints.java });
    if (!env.maven) return resolve({ ok: false, error: 'Maven не установлен. Выполните: ' + env.hints.maven });

    const cmd = process.platform === 'win32' ? 'mvn.cmd' : 'mvn';
    const proc = spawn(cmd, ['-q', '-B', 'package'], { cwd: dir, shell: process.platform === 'win32' });
    let log = '';
    const push = (d) => { log += d; onLog && onLog(String(d)); };
    proc.stdout.on('data', push);
    proc.stderr.on('data', push);
    const timer = setTimeout(() => { proc.kill(); resolve({ ok: false, error: 'Таймаут сборки (10 мин)', log }); }, 600000);
    proc.on('close', (code) => {
      clearTimeout(timer);
      const jar = findJar(dir);
      resolve(code === 0 && jar
        ? { ok: true, jar, log }
        : { ok: false, error: 'Сборка завершилась с ошибкой (код ' + code + ')', log });
    });
    proc.on('error', (e) => { clearTimeout(timer); resolve({ ok: false, error: e.message, log }); });
  });
}

function deleteProject(name) {
  const dir = path.join(mcRoot(), name.replace(/[^a-zA-Z0-9_-]/g, ''));
  if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
  return { ok: true };
}

const MOD_LOADERS = {
  fabric: { label: 'Fabric мод', desc: 'Лёгкий мод-лоадер Fabric (Gradle).' },
  forge: { label: 'Forge мод', desc: 'Классический мод-лоадер Forge (Gradle).' }
};

// Создание скелета мода Forge/Fabric (Gradle-проект).
function createMod({ name, loader = 'fabric', mcVersion = '1.21.1', author = 'MytheraAI' }) {
  const safe = name.replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 40) || 'MyMod';
  const id = safe.toLowerCase();
  const cls = javaClassName(safe);
  const pkg = 'com.mythera.' + id;
  const dir = path.join(mcRoot(), safe);
  if (fs.existsSync(dir)) return { ok: false, error: 'Проект с таким именем уже существует' };
  const javaDir = path.join(dir, 'src/main/java', ...pkg.split('.'));
  const resDir = path.join(dir, 'src/main/resources');
  fs.mkdirSync(javaDir, { recursive: true });
  fs.mkdirSync(resDir, { recursive: true });

  if (loader === 'fabric') {
    fs.writeFileSync(path.join(dir, 'build.gradle'), `plugins { id 'fabric-loom' version '1.7-SNAPSHOT'; id 'java' }
version = '1.0.0'
group = '${pkg}'
base { archivesName = '${id}' }
repositories { mavenCentral() }
dependencies {
  minecraft "com.mojang:minecraft:${mcVersion}"
  mappings "net.fabricmc:yarn:${mcVersion}+build.1:v2"
  modImplementation "net.fabricmc:fabric-loader:0.16.0"
}
java { sourceCompatibility = JavaVersion.VERSION_21; targetCompatibility = JavaVersion.VERSION_21 }
`);
    fs.writeFileSync(path.join(dir, 'settings.gradle'), `pluginManagement { repositories { maven { url 'https://maven.fabricmc.net/' }; gradlePluginPortal() } }\nrootProject.name = '${id}'\n`);
    fs.writeFileSync(path.join(dir, 'gradle.properties'), `org.gradle.jvmargs=-Xmx2G\n`);
    fs.writeFileSync(path.join(resDir, 'fabric.mod.json'), JSON.stringify({
      schemaVersion: 1, id, version: '1.0.0', name: safe, description: 'Mod by Mythera AI Hub', authors: [author],
      environment: '*', entrypoints: { main: [`${pkg}.${cls}`] }, depends: { fabricloader: '>=0.16.0', minecraft: `~${mcVersion}` }
    }, null, 2));
    fs.writeFileSync(path.join(javaDir, cls + '.java'), `package ${pkg};

import net.fabricmc.api.ModInitializer;

public class ${cls} implements ModInitializer {
    @Override
    public void onInitialize() {
        System.out.println("[${safe}] Fabric mod initialized!");
    }
}
`);
  } else {
    // Forge
    fs.writeFileSync(path.join(dir, 'build.gradle'), `plugins { id 'net.minecraftforge.gradle' version '6.0.+'; id 'java' }
version = '1.0.0'
group = '${pkg}'
java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }
minecraft { mappings channel: 'official', version: '${mcVersion}' }
repositories { mavenCentral() }
dependencies { minecraft 'net.minecraftforge:forge:${mcVersion}-latest' }
jar { manifest { attributes(['Specification-Title': '${id}']) } }
`);
    fs.writeFileSync(path.join(dir, 'settings.gradle'), `pluginManagement { repositories { gradlePluginPortal(); maven { url = 'https://maven.minecraftforge.net/' } } }\nrootProject.name = '${id}'\n`);
    fs.writeFileSync(path.join(dir, 'gradle.properties'), `org.gradle.jvmargs=-Xmx3G\n`);
    const metaDir = path.join(resDir, 'META-INF'); fs.mkdirSync(metaDir, { recursive: true });
    fs.writeFileSync(path.join(metaDir, 'mods.toml'), `modLoader="javafml"\nloaderVersion="[47,)"\nlicense="MIT"\n[[mods]]\nmodId="${id}"\nversion="1.0.0"\ndisplayName="${safe}"\nauthors="${author}"\ndescription="Mod by Mythera AI Hub"\n`);
    fs.writeFileSync(path.join(javaDir, cls + '.java'), `package ${pkg};

import net.minecraftforge.fml.common.Mod;

@Mod("${id}")
public class ${cls} {
    public ${cls}() {
        System.out.println("[${safe}] Forge mod loaded!");
    }
}
`);
  }
  return { ok: true, name: safe, dir, loader, mainClass: `${pkg}.${cls}` };
}

// Компиляция мода через Gradle.
function compileMod(name, onLog) {
  return new Promise(async (resolve) => {
    const dir = path.join(mcRoot(), name);
    if (!fs.existsSync(path.join(dir, 'build.gradle'))) return resolve({ ok: false, error: 'build.gradle не найден' });
    const env = await checkEnv();
    if (!env.java) return resolve({ ok: false, error: 'Java (JDK 21) не установлена. Выполните: ' + env.hints.java });
    const wrapper = process.platform === 'win32' ? 'gradlew.bat' : './gradlew';
    const useWrapper = fs.existsSync(path.join(dir, process.platform === 'win32' ? 'gradlew.bat' : 'gradlew'));
    if (!useWrapper && !env.gradle) return resolve({ ok: false, error: 'Gradle не установлен. Выполните: ' + env.hints.gradle });
    const cmd = useWrapper ? wrapper : (process.platform === 'win32' ? 'gradle.bat' : 'gradle');
    const proc = spawn(cmd, ['build', '--no-daemon'], { cwd: dir, shell: process.platform === 'win32' });
    let log = '';
    const push = (d) => { log += d; onLog && onLog(String(d)); };
    proc.stdout.on('data', push); proc.stderr.on('data', push);
    const timer = setTimeout(() => { proc.kill(); resolve({ ok: false, error: 'Таймаут сборки (15 мин)', log }); }, 900000);
    proc.on('close', (code) => {
      clearTimeout(timer);
      const jar = findJar(dir);
      resolve(code === 0 && jar ? { ok: true, jar, log } : { ok: false, error: 'Сборка завершилась с ошибкой (код ' + code + '). Модам нужен интернет для скачивания зависимостей при первой сборке.', log });
    });
    proc.on('error', (e) => { clearTimeout(timer); resolve({ ok: false, error: e.message, log }); });
  });
}

/* ------ Инструменты для агентов ------ */
const toolSchemas = [
  { type: 'function', function: { name: 'mc_create_plugin', description: 'Создать новый проект плагина Minecraft (Paper/Spigot) из шаблона. Шаблоны: basic, command, listener.', parameters: { type: 'object', properties: { name: { type: 'string' }, template: { type: 'string' }, mcVersion: { type: 'string' } }, required: ['name'] } } },
  { type: 'function', function: { name: 'mc_compile_plugin', description: 'Скомпилировать проект плагина Minecraft в .jar через Maven. Возвращает путь к jar или лог ошибок.', parameters: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'] } } },
  { type: 'function', function: { name: 'mc_list_plugins', description: 'Показать список проектов плагинов и модов Minecraft.', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'mc_create_mod', description: 'Создать мод Minecraft для Forge или Fabric (Gradle-проект). loader: forge | fabric.', parameters: { type: 'object', properties: { name: { type: 'string' }, loader: { type: 'string' }, mcVersion: { type: 'string' } }, required: ['name', 'loader'] } } },
  { type: 'function', function: { name: 'mc_compile_mod', description: 'Скомпилировать мод (Forge/Fabric) в .jar через Gradle.', parameters: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'] } } }
];

const toolHandlers = {
  async mc_create_plugin(args) {
    const r = createProject(args);
    return r.ok ? `Проект создан: ${r.dir}\nГлавный класс: ${r.mainClass}\nИсходники можно править через write_file.` : 'Ошибка: ' + r.error;
  },
  async mc_compile_plugin({ name }) {
    const r = await compileProject(name, null);
    return r.ok ? 'Готово! JAR: ' + r.jar : 'Ошибка сборки: ' + r.error + '\n' + String(r.log || '').slice(-1500);
  },
  async mc_list_plugins() {
    const list = listProjects();
    return list.length ? list.map((p) => `${p.name} [${p.kind}]${p.jar ? ' собран: ' + p.jar : ''}`).join('\n') : 'Проектов нет.';
  },
  async mc_create_mod(args) {
    const r = createMod(args);
    return r.ok ? `Мод (${r.loader}) создан: ${r.dir}\nГлавный класс: ${r.mainClass}` : 'Ошибка: ' + r.error;
  },
  async mc_compile_mod({ name }) {
    const r = await compileMod(name, null);
    return r.ok ? 'Готово! JAR: ' + r.jar : 'Ошибка сборки: ' + r.error + '\n' + String(r.log || '').slice(-1500);
  }
};

module.exports = { mcRoot, checkEnv, listProjects, createProject, compileProject, createMod, compileMod, deleteProject, TEMPLATES, MOD_LOADERS, toolSchemas, toolHandlers };
